# site_name: Žiga's Blog
# theme:
#   name: material
#   features:
#     - navigation.sections
# plugins:
#   - blog:
#       blog_dir: . 
# nav:
#   - index.md

# theme:
#   logo: img/white-logo.png
#   favicon: img/white-logo.png
#   name: material
#   palette:
#     - primary: black
#      # Palette toggle for light mode
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode

#     # Palette toggle for dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
#           # logo: img/logo.png
#   features:
#     # - navigation.tabs
#     - navigation.expand


site_name: Žiga's Blog
site_url: https://zzigak.github.io/blog
theme:
  name: material
  logo: img/white-logo.png
  favicon: img/white-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: indigo


# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

# copyright: |
#   &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>
